package top.jlen.vod.ui

import androidx.compose.runtime.Composable
import top.jlen.vod.data.FindPasswordEditor
import top.jlen.vod.data.MembershipPlan
import top.jlen.vod.data.RegisterEditor
import top.jlen.vod.data.UserProfileEditor

@Composable
fun AccountScreen(
    state: AccountUiState,
    onUserNameChange: (String) -> Unit,
    onPasswordChange: (String) -> Unit,
    onLogin: () -> Unit,
    onLogout: () -> Unit,
    onCheckUpdate: () -> Unit,
    onSelectSection: (AccountSection) -> Unit,
    onRefreshSection: () -> Unit,
    onChangePortrait: () -> Unit,
    onOpenHistoryRecord: (top.jlen.vod.data.UserCenterItem) -> Unit,
    onOpenFollow: () -> Unit,
    onLoadMoreHistory: () -> Unit,
    onDeleteHistory: (String) -> Unit,
    onClearHistory: () -> Unit,
    onUpgradeMembership: (MembershipPlan) -> Unit,
    onSignInMembership: () -> Unit,
    onOpenPointLogs: () -> Unit,
    onProfileEditorChange: ((UserProfileEditor) -> UserProfileEditor) -> Unit,
    onProfileTabChange: (Boolean) -> Unit,
    onSaveProfile: () -> Unit,
    onAuthModeChange: (AccountAuthMode) -> Unit,
    onRegisterEditorChange: ((RegisterEditor) -> RegisterEditor) -> Unit,
    onRefreshRegisterCaptcha: () -> Unit,
    onSendRegisterCode: () -> Unit,
    onRegister: () -> Unit,
    onFindPasswordEditorChange: ((FindPasswordEditor) -> FindPasswordEditor) -> Unit,
    onRefreshFindPasswordCaptcha: () -> Unit,
    onFindPassword: () -> Unit,
    onSendEmailCode: () -> Unit,
    onBindEmail: () -> Unit,
    onUnbindEmail: () -> Unit,
    onRefreshCrashLog: () -> Unit,
    onClearCrashLog: () -> Unit
) = LegacyAccountScreen(
    state = state,
    onUserNameChange = onUserNameChange,
    onPasswordChange = onPasswordChange,
    onLogin = onLogin,
    onLogout = onLogout,
    onCheckUpdate = onCheckUpdate,
    onSelectSection = onSelectSection,
    onRefreshSection = onRefreshSection,
    onChangePortrait = onChangePortrait,
    onOpenHistoryRecord = onOpenHistoryRecord,
    onOpenFollow = onOpenFollow,
    onLoadMoreHistory = onLoadMoreHistory,
    onDeleteHistory = onDeleteHistory,
    onClearHistory = onClearHistory,
    onUpgradeMembership = onUpgradeMembership,
    onSignInMembership = onSignInMembership,
    onOpenPointLogs = onOpenPointLogs,
    onProfileEditorChange = onProfileEditorChange,
    onProfileTabChange = onProfileTabChange,
    onSaveProfile = onSaveProfile,
    onAuthModeChange = onAuthModeChange,
    onRegisterEditorChange = onRegisterEditorChange,
    onRefreshRegisterCaptcha = onRefreshRegisterCaptcha,
    onSendRegisterCode = onSendRegisterCode,
    onRegister = onRegister,
    onFindPasswordEditorChange = onFindPasswordEditorChange,
    onRefreshFindPasswordCaptcha = onRefreshFindPasswordCaptcha,
    onFindPassword = onFindPassword,
    onSendEmailCode = onSendEmailCode,
    onBindEmail = onBindEmail,
    onUnbindEmail = onUnbindEmail,
    onRefreshCrashLog = onRefreshCrashLog,
    onClearCrashLog = onClearCrashLog
)
